index:
    controller: App\Controller\TestController::index
    path: /

# test:
#     path: /test/{age<\d+>?0}
#     controller: App\Controller\TestController::test     
#     defaults: # raccourcis dans le paramettre age {age?0}
#         # age: 0
#     # requirements: # raccourcis {age<\d+>}
#         # age: \d+
